server:
  port: 8082
  multipart:
    enabled: true
    maxFileSize: 1024MB
    maxRequestSize: 1024MB
  tomcat:
    max-http-header-size: 8192


upload:
  path: /home/spring_server/uploads/

# DataSource Config
spring:
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filter: stat
      #mysql驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
#      url: jdbc:mysql://47.106.223.246:80/site_server?characterEncoding=utf-8
      url: jdbc:mysql://xxx:xx/site_server?characterEncoding=utf-8
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
  mvc:
    static-path-pattern:  /**
    resources: static-locations:classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xwdz.site.entity


# 返回HTML 配置
thymeleaf:
  prefix: classpath:/templates/
  check-template-location: true
  suffix: .html
  encoding: UTF-8
  mode: LEGACYHTML5
  cache: false

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
